### ISSUE TITLE
Add more grouped reductions for flox

### ISSUE THREAD

**Issue by dcherian** [numbagg/numbagg#120]
(also non-NaN versions of these)

This is in approximate decreasing priority order.

- [x] `nanlen` = xarray's `count`
- [x] `nanargmax`, `nanargmin`
- [x] `nanfirst`, `nanlast`
- [x] `nansum_of_squares`
- [x] `nanprod`
- [x] all, any
- [x] nanvar
- [x] nanstd
- [x] nanmax, nanmin
- [ ] non-NaN skipping versions

**Comment by max-sixty** [comment]
Ack! These shouldn't be too hard. We have the plain functions for most of these, just need to convert them to the grouped versions. (I might even see whether an LLM can help...)

> (also non-NaN versions of these)

Do we need non-nan versions? We basically have none of those at the moment, and I think it would be inelegant duplication to do them. (But not hard...)

**Comment by dcherian** [comment]
> Do we need non-nan versions? 

Interesting q. I was thinking there might be a speedup from avoiding the isnan branch in the inner loop

**Comment by max-sixty** [comment]
> Interesting q. I was thinking there might be a speedup from avoiding the isnan branch in the inner loop

I think there likely would be, but:
- It might be quite small, since it'll start getting branch-predicted away quite quickly when it's always false (and maybe even compiled away on non-nullable dtypes?)
- I would vote to ship the minimum and then add things like this later. The current routines are already 3-4x faster than pandas where I've benchmarked them. And adding duplication adds to the overhead changes is more difficult. So to the extent that you're happy to ship and then we add later if needed, that would be ideal...

**Comment by dcherian** [comment]
Ah a bigger issue is that `np.nansum([np.nan, np.nan]) = 0` but `np.sum([np.nan, np.nan]) = np.nan)`

**Comment by max-sixty** [comment]
> Ah a bigger issue is that `np.nansum([np.nan, np.nan]) = 0` but `np.sum([np.nan, np.nan]) = np.nan)`

Good point...

How used are the non-nan versions? I think in xarray we always call the nan versions?

**Comment by dcherian** [comment]
> I think in xarray we always call the nan versions?

by default except for types that can't have NaNs

**Comment by max-sixty** [comment]
> `skipna=True` by default except for types that can't have NaNs

The types that can't have NaNs always have the same result though, right? It's only possible to have the `np.sum([np.nan, np.nan]) = np.nan)` for null-able types...

So I guess at the moment this could be an exception for `skipna=False`, but otherwise OK? (even if not optimally fast, though still a >2x speed-up...)

**Comment by dcherian** [comment]
> The types that can't have NaNs always have the same result though, right? 

yes.

> o I guess at the moment this could be an exception for skipna=False, but otherwise OK?

I'm not following your train of thought here.

**Comment by max-sixty** [comment]
> > o I guess at the moment this could be an exception for skipna=False, but otherwise OK?
> 
> I'm not following your train of thought here.

Sorry — I'm mixing two concepts:
- We're always OK for anything called by xarray — we call "skipna=True by default except for types that can't have NaNs". And for types that can't have NaNs, numbagg always returns the correct result.
- We can raise on `skipna=False` in flox to ensure we never return an incorrect result, even when getting a non-default-xarray call.

The annoyance will be if we're calling `skipna=False` on ints from xarray, and this raises, despite the underlying function being OK.

**Comment by max-sixty** [comment]
Funnily enough I just did the final 4 there! I will push later!

**Comment by max-sixty** [comment]
@dcherian just for transparency — I'm not totally happy about how well numbagg supports different types, and I've seen some odd behavior as to whether ints are changed into floats, etc.

I'm quite happy about the main code path of "group floats".

I'm prioritizing responsiveness over depth — so if we see some oddities around the edges, report it and I'll take a look quickly... but it wouldn't be representative of how reliable the main code path is.

**Comment by dcherian** [comment]
> I'm prioritizing responsiveness over depth

Thank you!

The flox tests are relatively thorough, so I'll be finding a lot of edge cases =)

**Comment by max-sixty** [comment]
I think these are all done! We don't have non-nan-skipping versions, but a) there isn't much / any perf benefit, because memory is slow and branch prediction is so good, b) even if that weren't the case, I would wait for a demand signal before implementing, since it would be a lot of copy-pasta...
