### ISSUE TITLE
Abstract groupby function?

### ISSUE THREAD

**Issue by max-sixty** [numbagg/numbagg#13]
I had a quick go at abstracting the groupby function to be abstract over the reduction function 

This (almost*) works - we could pass in `np.nanmean` / `np.nanstd` and easily generate a bunch of these functions

But not sure whether the performance would be materially worse?

```python

@groupndreduce([
    (float64, int64, float64),
    (float64, int32, float64),
    (float32, int64, float32),
    (float32, int32, float32),
])
def group_nanmean(values, labels, out):
    labels = labels.ravel()
    values = values.ravel()
    grouped = []
    for i in range(out.size):
        # nan required in order to satisfy numba types
        grouped.append([np.nan])

    for i in range(values.size):
        l = labels[i]
        v = values[i]
        grouped[l].append(v)

    for i in range(out.size):
        group = grouped[i]
        out[i] = np.nanmean(np.array(group))
```

\* The final item in the array is incorrect - I'm missing something elementary, but doubt it's a showstopper and wanted to socializing the concept

**Comment by max-sixty** [comment]
Updated with the actual abstraction, and fixed the minor issue above

```python
def group_wrapper(func):
    @groupndreduce([
        (float64, int64, float64),
        (float64, int32, float64),
        (float32, int64, float32),
        (float32, int32, float32),
    ])
    def group_func(values, labels,  out):
        labels = labels.ravel()
        values = values.ravel()
        grouped = []
        for i in range(out.size):
            # nan required in order to satisfy numba type inference
            grouped.append([np.nan])

        for l, v in zip(labels, values):
            if l >= 0:
                grouped[l].append(v)

        for i in range(out.size):
            group = grouped[i]
            out[i] = func(np.array(group))

    return group_func


group_nanmean = group_wrapper(np.nanmean)
group_nansum = group_wrapper(np.nansum)
group_nanstd = group_wrapper(np.nanstd)
```

**Comment by max-sixty** [comment]
Ah, but unfortunately not so fast:

```python

[ins] In [1]: import numbagg
         ...: import numpy as np
         ...: import bottleneck
         ...:


[nav] In [29]:     rs = np.random.RandomState(0)
          ...:     values = rs.rand(2000000)
          ...:     group = rs.choice([0, 1, 2, 3, 4, 5], size=values.shape)


[ins] In [33]: %timeit numbagg.group_nanmean(values,group)
59.5 ms ± 678 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


[ins] In [35]: %timeit pd.Series(values).groupby(group).mean()
20.2 ms ± 507 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

On the existing implementation:

```python

[ins] In [7]: %timeit numbagg.group_nanmean(values,group)
4.41 ms ± 360 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

My understanding is that the Numba-list is a reasonably fast implementation (it's not like using a python list), but even if so, building the list and then reducing adds a decent amount of overhead

**Comment by shoyer** [comment]
This could be an OK fall-back implementation, but indeed, it will be pretty slow due to all the unnecessary and repeated memory allocation. Most reductions (with notable exception of an exact median) can be completed by allocating some constant amount of memory per element. If we can do all the memory allocation once, up front, that significantly speeds things up.

Note that we could probably improve the speed of existing methods by allocating the `counts` array once, outside the gufunc's inner loop.

**Comment by max-sixty** [comment]
Closing as not a great idea. We have one idea from the feedback here in #13 though!
