### ISSUE TITLE
Support factorizing?

### ISSUE THREAD

**Issue by dcherian** [numbagg/numbagg#133]
It'd be interesting to see if numbagg can beat `pd.factorize`.

`flox` uses `np.searchsorted`, `np.digitize` and `pd.factorize` here:
https://github.com/xarray-contrib/flox/blob/486b7c5fb4324ddad48e9a00c0b88638f3e65471/flox/core.py#L502

This section of the code takes up 30-40% of any groupby problem IIRC, so this could be a decent win.

**Comment by dcherian** [comment]
I'll also note that xarray currently calls `pd.factorize` or `pd.cut` always and passes integer group labels to flox. So we could dispatch to numbagg there too.

**Comment by max-sixty** [comment]
Yes agree, would be a fun one.

What types would we need to support? Is just primitive types OK (including `str`)? Or we'd need to support arbitrary classes?

**Comment by max-sixty** [comment]
One issue is that I don't think it could be a gufunc, given that gufuncs require fixed output sizes. And padding the output would be quite wasteful.

There's an issue at https://github.com/numba/numba/issues/2797 — though regardless of numba, I don't think it's theoretically possible, given that the lengths of the arrays would be different for different slices.

Though this isn't terminal — we could still get value from a non-gufunc version.

**Comment by max-sixty** [comment]
FYI a quick check suggests the pandas version is extremely performant already. With a naive numba implementation, I get something about 1/3 as fast.

**Comment by max-sixty** [comment]
I think this is basically in a local optimum atm. To find a better approach, numba would need to be much faster with dicts, or we'd have to rewrite in a language such as rust. And I have no confidence that we'd be faster than `pd.factorize` in either of those cases.

...which is some ways is disappointing, because numba is much nicer than cython IMO, and it would be cool to allow for full groupby functionality without a pandas dependency. 

But impressive that pandas is so fast here! 

If anyone else wants to take a look, here's the quick numba approach from an LLM:

```python
import numpy as np
import pandas as pd
from numba import jit

@jit(nopython=True)
def factorize_numba(arr):
    # Create an empty dictionary to store unique values and their codes
    unique_dict = {}
    codes = np.empty(arr.shape[0], dtype=np.int64)
    next_code = 0

    # Iterate over the array and assign codes
    for i, value in enumerate(arr):
        if value not in unique_dict:
            unique_dict[value] = next_code
            next_code += 1
        codes[i] = unique_dict[value]

    # Extract the unique values in the order they appeared
    uniques = np.array(list(unique_dict.keys()))

    return codes, uniques

# Test the function to check its correctness
test_array = np.array(["a", "b", "a", "c", "b", "c", "d"])
codes_numba, uniques_numba = factorize_numba(test_array)
codes_pd, uniques_pd = pd.factorize(test_array)

codes_numba, uniques_numba, codes_pd.tolist(), uniques_pd.tolist()
```
