### ISSUE TITLE
Add `llvm-openmp` or `tbb` as dependency in conda-forge

### ISSUE THREAD

**Issue by dcherian** [numbagg/numbagg#209]
[Continuing the `target="parallel"` [conversation](https://github.com/numbagg/numbagg/pull/201) here.]

IIUC:
1. Numba supports 3 threading layers `tbb`, `openmp`, `workqueue` (built-in).
1. `workqueue` is not thread-safe, so numba aborts if trying to run with the default dask scheduler.
1. From the Numba [docs](https://numba.readthedocs.io/en/stable/user/threading-layer.html#which-threading-layers-are-available):
    > The OpenMP threading layer is disabled in the Numba binary wheels on PyPI.
1. The `tbb` PyPI package is [only distributed](https://pypi.org/project/tbb/2021.11.0/#files) for windows and linux, not macos, but it is available through conda-forge (🤷🏾‍♂️ !!!)

So the only cross-platform solution with `pip` is to pursue the current and expensive approach of switching to `target="cpu"`. 
On `conda-forge` I propose we add either `tbb` or `llvm-openmp` as a required dependency so users installing through conda (a large number?) get a better experience.

**Comment by dcherian** [comment]
Ah the piece I haven't figured out yet is detecting which threading layers are installed and the gating the `target="cpu"` branch on that. But presumably this is possible somehow.

**Comment by dcherian** [comment]
Well i tracked `numba -s` to https://github.com/numba/numba/blob/main/numba/misc/numba_sysinfo.py

```python
from numba.misc.numba_sysinfo import get_sysinfo

info = get_sysinfo()
has_tbb = info["TBB Threading"]
has_omp = info["OpenMP Threading"]
has_wkq = info["Workqueue Threading"]

if not (has_tbb | has_omp) and has_wkq:
	target = "cpu"
```

**Comment by max-sixty** [comment]
Amazing, thanks a lot for thinking through this!

Agree this sounds like a great solution.

One downside is that `info = get_sysinfo()` takes 717ms. But maybe we only call it:
- When we detect we're in multithreading, using the thread name, like we do now
- Once — if we keep the existing "downgrade to cpu permanently", this would happen anyway

> On `conda-forge` I propose we add either `tbb` or `llvm-openmp` as a required dependency so users installing through conda (a large number?) get a better experience.

I agree — do you know offhand how we can do this for conda only? I can look otherwise

**Comment by dcherian** [comment]
> One downside is that info = get_sysinfo() takes 717ms.

It isn't changing in a session, so we can call it at import time! or at least we don;t have to support it changing in a session

> do you know offhand how we can do this for conda only?

we add it here: https://github.com/conda-forge/numbagg-feedstock/blob/main/recipe/meta.yaml

**Comment by max-sixty** [comment]
> It isn't changing in a session, so we can call it at import time! or at least we don;t have to support it changing in a session

I def think we should limit it to when we're in multithreading, and not on all imports

(and not at import time, since often that's before someone has started a multithreading pool)

**Comment by dcherian** [comment]
I mean you can get `sysinfo` at import-time once.

**Comment by max-sixty** [comment]
Gosh, yeah, 490ms on mine, with `python -X importtime`!

Yep, the backend check is only 180ms, that is better...

**Comment by max-sixty** [comment]
> On `conda-forge` I propose we add either `tbb` or `llvm-openmp` as a required dependency so users installing through conda (a large number?) get a better experience.

It seems that numba already includes `tbb` actually — https://github.com/conda-forge/numba-feedstock/blob/172c489224b795438fdbf289d04cbc188ddb480a/recipe/meta.yaml#L81 — so possibly we're covered there. (I also think that conceptually it makes sense for numba to own that dependency; numbagg isn't really doing anything special, despite being a source of complaints :smile: )

**Comment by max-sixty** [comment]
OK great!
