### ISSUE TITLE
`nanquantiles` should only accept quantiles between 0 and 1

### ISSUE THREAD

**Issue by maawoo** [numbagg/numbagg#276]
Currently, the function also accepts negative values >= -1. 
I think this should be aligned with numpy, see [here](https://github.com/numpy/numpy/blob/d35cd07ea997f033b2d89d349734c61f5de54b0d/numpy/lib/function_base.py#L4541-L4542).

**Comment by max-sixty** [comment]
Thanks @maawoo ! Closed by #277
