### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by max-sixty** [numbagg/numbagg#37]
Assuming [this](https://github.com/shoyer/numbagg/issues/36) isn't an issue, shall we release 0.2.0 with rolling exp sum?

CC @shoyer — I'm happy to do it if you agree

**Comment by shoyer** [comment]
Yes, please go ahead!

**Comment by astrojuanlu** [comment]
0.2.0 and 0.2.1 were released back in May https://github.com/numbagg/numbagg/releases/tag/v0.2.1 I guess this can be closed?

**Comment by astrojuanlu** [comment]
0.2.0 and 0.2.1 were released back in May https://github.com/numbagg/numbagg/releases/tag/v0.2.1 I guess this can be closed?
